apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: phoenix-workspace
  namespace: kommander
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile-order: "1"
spec:
  interval: 5s
  path: ./kustomizations/workspaces
  prune: true
  sourceRef:
   kind: GitRepository
   name: phoenix-cluster-gitops
   namespace: kommander