apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: phoenix-workload
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: phoenix-workload
    konvoy.d2iq.io/provider: nutanix
    topology.cluster.x-k8s.io/owned: ""
  name: phoenix-workload
  #namespace has to match the workspace namespace
  namespace: phoenix-workspace
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: "10.168.102.44"
    port: 6443
  topology:
    class: nkp-nutanix-v2.14.0
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: phoenix-workload-pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: phoenix-workload-pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: false
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for phoenix-workload
                      hypervisorAttached: DISABLED
                      storageContainer: SelfServiceContainer
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                    volumeBindingMode: WaitForFirstConsumer
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - start: 10.168.102.45
                end: 10.168.102.45
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: WSKN-NONGPU
                type: name
              image:
                name: nkp-rocky-9.5-release-1.31.4-20250214003015.qcow2
                type: name
              memorySize: 16Gi
              project:
                name: Default
                type: name
              subnets:
              - name: NONGPU-Primary
                type: name
              systemDiskSize: 120Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          credentials:
            secretRef:
              name: phoenix-workload-image-registry-mirror-credentials
          url: https://registry.wskn.local/mirror
        nutanix:
          controlPlaneEndpoint:
            host: 10.168.102.44
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: phoenix-workload-pc-credentials
            insecure: false
            url: https://pc.wskn.local:9440
            additionalTrustBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKakNDQWc2Z0F3SUJBZ0lRTkJ0MU9jYkVXb2NFbGlwMGxKamV6ekFOQmdrcWhraUc5dzBCQVFzRkFEQVgKTVJVd0V3WURWUVFERXd4M2MydHVMWEp2YjNRdFkyRXdIaGNOTWpVd05EQTNNRE13TkRFM1doY05NelV3TkRBMwpNVFV3TkRFM1dqQWZNUjB3R3dZRFZRUURFeFIzYzJ0dUxXbHVkR1Z5YldWa2FXRjBaUzFqWVRDQ0FTSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU1MN3pEaTZyWFlOUDRoY3Z2WFg4cWhYN0VCODgxT3IKK2U4RVlOWlUzc0VNZTlFUW9taUJzYnRaTTRkYlVJMDlVdk9JNmJBTVM2UDZXL1cvUFZWenBhR3JMQzBUTDNwcwpoU0VyYjNIVCtqLzQyZ051TVdpOHlEUXlHWEJxdFkrOGFRUy9NS0ZyZnVjUWpMQ0g4eGV2a29KZmVnTEc0RTRECnY3K0JVbXB6dUlacTNRRnprNVgyZG5zeW1IQTVueGYxOXBJNG1LRFJ2NGw0V25aa2orNS9TZ0FaRStYMnpVNUgKMjZPVTNJemo5cWNlemdUZXNDN055NnZBeitxNnpFWmtnQitTT0dPbDRkMXh3M2tDMXZMT2tBMFI1eGs2eHMySApGSFRUdGpscDJ6NEFwRWlJZTYzUHJpOUtWQ0Y5cFphdEVTNEJNQTV6Vkx6RllNMCtlblNVVERjQ0F3RUFBYU5tCk1HUXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRQXdIUVlEVlIwT0JCWUUKRkdSL2VRVGdRbE5Pc25tZmlEOFFueGFUYWQ4WE1COEdBMVVkSXdRWU1CYUFGUGdNSlc5c3E2cFFHeVhyUUxDdwp6dkR1OUs3NU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTh6T0RoVmgxUk5rNjRmWG1OOFY5ejNKTEpGemVUCk9NU0RMYkhYZ3JSRjFkL1d4eHFKOHZzRmcyUEpPWjdtbGZIWE0yY0RmR1BIZWJ3TnVnVUJxTU4ySUtMdTFCeGgKV0lZeUhDT0xOMzFiN0VWblN3VVg5bGRCVFFLbjFsK09wK1VPaGpWblBFYVZXSUg0Z09WRXhwV2lFOE01V1p4SApwSkVFck5adXdKSzNPSExQVUpSUnR4WWFkNGNKN2ZGSnFiNXo0MDdVR1k4YUdlb25pM0pOZGo5SVZaWjFDUjIxCmtKemRERXV5YjVyTkZZK3dlYW5Db2ozb2FyaXUyK0NEa2V0TFJwWWNoV0tkaU9VMzlyRHhXbXdrd1MxZ1RUU20KNkhCaWZGWnhCT2FhL0hwVUh2djIzK2N1djdVY3Bsd0x3cE1FbmFpVEszUm5DTmtONDdLeFBBTmsKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQy9UQ0NBZVdnQXdJQkFnSVFPUHBndjJFbldYNUlnSUUwRkVNZVpEQU5CZ2txaGtpRzl3MEJBUXNGQURBWApNUlV3RXdZRFZRUURFd3gzYzJ0dUxYSnZiM1F0WTJFd0hoY05NalV3TkRBM01ETXdOREUxV2hjTk16VXdOREEzCk1UVXdOREUxV2pBWE1SVXdFd1lEVlFRREV3eDNjMnR1TFhKdmIzUXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNsL3RpYlhrRVN3K1JzYnBQbmZOSkVTdSt4YkpnK0hLTVJGcTBzbVBMVgpjc2ZlaWplY09aRUlHYndvaitjbHpxTWFmejNIR3RuTEdEVURyTjBIaFJlTUxZVVNpY3ZVa0VaT3JMMCtCUUx4Cnd3aEtHR2ZwMjFqM1FBSXBXQ09meGM5d2JRZE1KbUtSOGJISkZrOWlidTdJcUphVlhERVQzN2dhRU1TclM4V2MKODlwL3dJTi9ibEJmNDBwWElpSkMxZHV4OTJ4NTREVnFFTG1hTG5BODBjeDJhRHNFRktDdVJaM296aUw1YmxFZgpwaHpheGFtY1pTSnlOaWlOTGdLYmZWRzNHUjNNTFhKajErZmFDQzMvajhJMXoyYXJhcjgzcDBZcDlBZ0w5c0gyCithRWFaK2RhVFRwanNVYzc2MXY4MnJ5Y3NieEU1ZjRwUmlzbm44NktxOHFuQWdNQkFBR2pSVEJETUE0R0ExVWQKRHdFQi93UUVBd0lCQmpBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQk1CMEdBMVVkRGdRV0JCVDREQ1Z2Ykt1cQpVQnNsNjBDd3NNN3c3dlN1K1RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUtNNE9wWThncnY5bUpVMWlUQzVwCjNpSXpGUmo3TnJyYk43c3JqU1ZRc1RLVjZjVTZrVkZqaHIwVEorclVkTzR3UXpBQXp2dkJOdERuMWhLRGhuSVMKOUE4YWc1dWZLaFdxNGJLdm9JdU9ablY5YktVY2JqK0c2OXRyOVBocEJJakV6dGR5d3VJbHR2Q1RmaTQrdHZldgpybFAzbkg4T2d4amdISkpXaTFmR041ZWtwaWJ5ZzRWOVFSY1YxZHBZSTk4MitSUEpwYlFDQm95YWtqbHVrMmdwCm90cFgxNnkyK015YXRwVXVIaWhLUzd3bExTTGxXU0Q0UXNxa05xeVFoWmpHcXBxZE5uQnpaUzN1UkJiRThEcmoKNGtkM0U1bDljK2t3SXNHMkdzVzM5d2g1QjhrWVBtdG9LWkNLVVh3dzN3eVVWOEJxZDAxbDNTUDVGMkZobGpvZAphQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        users:
        - name: konvoy
          sshAuthorizedKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDLysPovN+Ves5lJfbLzeIwnoPzwrR1tuyudV2mhLMYAuz7WpQIeV9QSrXLWMdD137Q3KvoxtNPXuck4M+oheZsMIRqlmYoxxWDpfXLdKEIrRrE6XI6DFSUrcUw4fXLL+1NLThx5uWCerGFBHXY8f7VxhqkNb7DkZP9oCI0id2Qn8NzA3es5li5j8DVrip3XS/Y14URinX9AlDYzKJEtTH0O2S3xi5q4xLbO2yhAarVfBQK06j2XWVmAPw2fC+Ny2+zjP97Y7AmRNUC644mFCdgjnd/mpmdRshvUdJKy6wgOeTTYdVuAeuHifvyamNcYJ+HCYYj0NPE72Av5tUPXiqb/czwTMQ6NoAqoEVAK5CiheNVjOp6OU348nLXiuCTU2oA44jSMWAzefwbi/dc5rzvfMXCobdjaMIfI9AG/K2EMvQK7WtaSMs7PYYM7x6Njkntq4WErp+i6k2XYSHydobUZh5M2ta5jDc9CUxXI4/G75lOyuBJAWljzPODBy8htcc= root@WSKN-LINUX01
          sudo: ALL=(ALL) NOPASSWD:ALL
    version: v1.31.4
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "4"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "4"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: WSKN-NONGPU
                    type: name
                  image:
                    name: nkp-rocky-9.5-release-1.31.4-20250214003015.qcow2
                    type: name
                  memorySize: 32Gi
                  project:
                    name: Default
                    type: name
                  subnets:
                  - name: NONGPU-Primary
                    type: name
                  systemDiskSize: 120Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1