apiVersion: v1
kind: ConfigMap
metadata:
  name: phoenix-crs-configmap
  namespace: phoenix-workspace  
data:
  git-repository.yaml: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    metadata:
      name: phoenix-gitops
      namespace: phoenix-workspace
    spec:
      interval: 1m0s
      url: https://github.com/WinsonSou/lazarus-cluster-gitops-pro.git
      ref:
        branch: main
  kustomization.yaml: |
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: phoenix-gitops
      namespace: phoenix-workspace
    spec:
      interval: 10m0s
      path: ./resources/workspaces/phoenix/cluster/namespaces
      prune: true
      sourceRef:
        kind: GitRepository
        name: phoenix-gitops